export const SET_FETCHING = 'SET_FETCHING';
export const UNSET_FETCHING = 'UNSET_FETCHING';

export const RECIEVE_AUTH = 'RECIEVE_AUTH';
export const AUTH_ERROR = 'AUTH_ERROR';

export const UPLOADING = 'UPLOADING';
export const END_UPLOADING = 'END_UPLOADING';

export const GET_USER_EVENTS = 'GET_USER_EVENTS';
export const GET_USER_EVENTS_ERROR = 'GET_USER_EVENTS_ERROR';

export const GET_ALL_EVENTS = 'GET_ALL_EVENTS';
export const GET_ALL_EVENTS_ERROR = 'GET_ALL_EVENTS_ERROR';
export const GET_FOLLOWING_STATUS = 'GET_FOLLOWING_STATUS';
export const SEARCH_EVENTS = 'SEARCH_EVENTS';
export const SEARCH_EVENTS_ERROR = 'SEARCH_EVENTS_ERROR';

export const GET_UPCOMING_EVENTS = 'GET_UPCOMING_EVENTS';
export const GET_UPCOMING_EVENTS_ERROR = 'GET_UPCOMING_EVENTS_ERROR';

export const GET_PAST_EVENTS = 'GET_PAST_EVENTS';
export const GET_PAST_EVENTS_ERROR = 'GET_PAST_EVENTS_ERROR';

export const GET_ONE_EVENT = 'GET_ONE_EVENT';
export const GET_ONE_EVENT_ERROR = 'GET_ONE_EVENT_ERROR';

export const GET_SUGGESTED_EVENTS = 'GET_SUGGESTED_EVENTS';
export const GET_SUGGESTED_EVENTS_ERROR = 'GET_SUGGESTED_EVENTS_ERROR';

export const EDIT_EVENT = 'EDIT_EVENT';
export const EDIT_EVENT_ERROR = 'EDIT_EVENT_ERROR';

export const DELETE_EVENT = 'DELETE_EVENT';
export const DELETE_EVENT_ERROR = 'DELETE_EVENT_ERROR';

export const ADD_EVENT = 'ADD_EVENT';
export const EVENT_ERROR = 'EVENT_ERROR';

export const SIGN_IN_USER = 'SIGN_IN_USER';
export const LOGOUT = 'LOGOUT';

export const LIKE_SUCCESS = 'LIKE_SUCCESS';
export const LIKE_FAILURE = 'LIKE_FAILURE';

export const FOLLOW_SUCCESS = 'FOLLOW_SUCCESS';
export const FOLLOW_FAILURE = 'FOLLOW_FAILURE';

export const UNFOLLOW_SUCCESS = 'UNFOLLOW_SUCCESS';
export const UNFOLLOW_FAILURE = 'UNFOLLOW_FAILURE';

export const ADD_UPDATE = 'ADD_UPDATE';
export const ADD_UPDATE_ERROR = 'ADD_UPDATE_ERROR';
export const GET_UPDATE = 'GET_UPDATE';
export const GET_UPDATE_ERROR = 'GET_UPDATE_ERROR';
export const DELETE_UPDATE = 'DELETE_UPDATE';
export const DELETE_UPDATE_ERROR = 'DELETE_UPDATE_ERROR';

export const GET_COMMENT_SUCCESS = 'GET_COMMENT_SUCCESS';
export const GET_COMMENT_FAILURE = 'GET_COMMENT_FAILURE';
export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS';
export const ADD_COMMENT_FAILURE = 'ADD_COMMENT_FAILURE';

export const EDIT_PROFILE = 'EDIT_PROFILE';
export const EDIT_PROFILE_ERROR = 'EDIT_PROFILE_ERROR';

export const GET_EVENT_DETAILS = 'GET_EVENT_DETAILS';
